/**
 * Billing Status Enum
 * Matches backend billing status values
 */
export enum BillingStatus {
  NO_PRICING = 'NO_PRICING',
  PRICING_PENDING = 'PRICING_PENDING',
  PRICED = 'PRICED',
  PRICE_DRAFTED = 'PRICE_DRAFTED',
  PI_GENERATED = 'PI_GENERATED',
  ADVANCE_PAID = 'ADVANCE_PAID',
  PRICE_SNAPSHOT = 'PRICE_SNAPSHOT',
  INVOICE_GENERATED = 'INVOICE_GENERATED',
  PAYMENT_PENDING = 'PAYMENT_PENDING',
  PAYMENT_PARTIAL = 'PAYMENT_PARTIAL',
  PAYMENT_COMPLETED = 'PAYMENT_COMPLETED'
}

