export enum SampleStatus {
  // --- INWARD / REGISTRATION ---
  SAMPLE_INWARD_REGISTERED = "SAMPLE_INWARD_REGISTERED",
  AWAITING_MISSING_INFORMATION = "AWAITING_MISSING_INFORMATION",
  INWARD_COMPLETED = "INWARD_COMPLETED",

  // --- PLANNING ---
  UNDER_PLANNING = "UNDER_PLANNING",

  // --- REVIEW OF REQUEST ---
  UNDER_REVIEW_REQUEST = "UNDER_REVIEW_REQUEST",
  REQUEST_REJECTED = "REQUEST_REJECTED",
  REQUEST_APPROVED = "REQUEST_APPROVED",

  // --- SAMPLE PREPARATION ---
  PREPARATION_REQUIRED = "PREPARATION_REQUIRED",
  PREPARATION_IN_PROGRESS = "PREPARATION_IN_PROGRESS",
  PREPARATION_COMPLETED = "PREPARATION_COMPLETED",

  // --- PI & PAYMENT ---
  PI_GENERATED = "PI_GENERATED",
  ADVANCE_PAYMENT_PENDING = "ADVANCE_PAYMENT_PENDING",
  ADVANCE_PAYMENT_COMPLETED = "ADVANCE_PAYMENT_COMPLETED",

  // --- TPI ---
  TPI_WAITING_FOR_AGENT = "TPI_WAITING_FOR_AGENT",
  TPI_IN_PROGRESS = "TPI_IN_PROGRESS",
  TPI_COMPLETED = "TPI_COMPLETED",

  // --- TESTING ---
  TESTING_IN_PROGRESS = "TESTING_IN_PROGRESS",
  TESTING_COMPLETED = "TESTING_COMPLETED",

  // --- TEST VERIFICATION ---
  TESTING_UNDER_VERIFICATION = "TESTING_UNDER_VERIFICATION",
  TESTING_VERIFICATION_REJECTED = "TESTING_VERIFICATION_REJECTED",
  TESTING_VERIFIED = "TESTING_VERIFIED",

  // --- REPORTING ---
  REPORT_GENERATION_IN_PROGRESS = "REPORT_GENERATION_IN_PROGRESS",
  REPORT_GENERATED = "REPORT_GENERATED",
  REPORT_UNDER_REVIEW = "REPORT_UNDER_REVIEW",
  REPORT_REJECTED_BY_INTERNAL = "REPORT_REJECTED_BY_INTERNAL",
  REPORT_AMENDED_BY_INTERNAL = "REPORT_AMENDED_BY_INTERNAL",
  REPORT_AMENDED_REJECTED = "REPORT_AMENDED_REJECTED",
  REPORT_AMENDMENT_APPROVED = "REPORT_AMENDMENT_APPROVED",

  // --- CUSTOMER REVIEW / AMENDMENT ---
  REPORT_SENT_FOR_CUSTOMER_REVIEW = "REPORT_SENT_FOR_CUSTOMER_REVIEW",
  CUSTOMER_REQUESTED_AMENDMENT = "CUSTOMER_REQUESTED_AMENDMENT",
  AMENDMENT_IN_PROGRESS = "AMENDMENT_IN_PROGRESS",
  AMENDMENT_COMPLETED = "AMENDMENT_COMPLETED",

  // --- PAYMENT (POST-REPORT) ---
  PAYMENT_PENDING = "PAYMENT_PENDING",
  PAYMENT_COMPLETED = "PAYMENT_COMPLETED",

  // --- FINAL APPROVAL & CLOSURE ---
  FINAL_REPORT_APPROVED = "FINAL_REPORT_APPROVED",
  REPORT_DISPATCHED = "REPORT_DISPATCHED",
  CASE_CLOSED = "CASE_CLOSED",

  // --- CANCELLED (terminal state) ---
  SAMPLE_CANCELLED = "SAMPLE_CANCELLED"
}
